### PR TITLE
chore: feat: remove both theia/latest and code/insiders (CRW-3489, CRW-4077)

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

chore: feat: remove both theia/latest and code/insiders (CRW-3489, CRW-4077)

Change-Id: I7cbde3c700c0616bf97dd2718cca31ba7a2ee689
Signed-off-by: Nick Boldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-3489 
https://issues.redhat.com/browse/CRW-3663 

See also 

https://issues.redhat.com/browse/CRW-4077

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by nickboldt** [comment]
See also https://github.com/redhat-developer/devspaces-images/pull/408

**Comment by nickboldt** [comment]
Note: PR checka is failing because I deleted a file it expects to exist: https://github.com/redhat-developer/devspaces/pull/911/files#diff-4c4b053554a0170b509c5113ab41ce10276680d179dd71688d014016b1b67f73

**Review by amisevsk — APPROVED** [review]

**Review by svor — CHANGES_REQUESTED** [review]
@nickboldt to keep the plugin registry image build successful, I'd like to finish [upstream chnages](https://github.com/eclipse-che/che-plugin-registry/pull/1607) that will provide a new version of **@eclipse-che/plugin-registry-generator**.

**Comment by nickboldt** [comment]
> I'd like to finish https://github.com/eclipse-che/che-plugin-registry/pull/1607 that will provide a new version of @eclipse-che/plugin-registry-generator.

Yeah, I'm not going to merge anything until che-plugin-reg is fully updated and merged w/ theia removals.

**Comment by nickboldt** [comment]
Obsoleted by other PRs

**Pull request closed without merging**
