### PR TITLE
chore: add vscode-dotnet-runtime extension

### PR DESCRIPTION
**Pull request by svor**
### What does this PR do?
Adds ms-dotnettools.vscode-dotnet-runtime extension into the list of embedded extensions as it is required by the latest version of muhammad-sammy.csharp

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-4835

### CODE REVIEW

**Review by ibuziuk — APPROVED** [review]

**Review by nickboldt — APPROVED** [review]
+1 as long as this is added to @SDawley 's list of things we build from source?

**Comment by svor** [comment]
PR to build vscode-dotnet-runtime extension from sources: https://github.com/redhat-developer/devspaces-vscode-extensions/pull/74
cc @SDawley

**Comment by SDawley** [comment]
Working on getting the plugin builds up and running again.
They are being difficult (again)

**Comment by svor** [comment]
> Failing due to
> 
> ```
> INFO - ❌  Cannot resolve dependency: ms-dotnettools.vscode-dotnet-runtime
> INFO - See the documentation for more information:
> INFO - https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
> INFO - 
> ERROR - Error: building at STEP "RUN chmod 777 /var/run/postgresql &&     initdb &&     /usr/local/bin/import_vsix.sh &&     chmod -R 777 /tmp/file &&     rm /var/lib/pgsql/15/data/database/postmaster.pid &&     rm /var/run/postgresql/.s.PGSQL* &&     rm /tmp/.s.PGSQL* &&     rm /tmp/.lock": while running runtime: exit status 1
> ```
> 
> -- https://download.eng.bos.redhat.com/brewroot/work/tasks/30/55210030/x86_64.log -- https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/get-sources-rhpkg-container-build_3.9/8/console

I missed that moment when 3.9 was created. When I have created a PR the branch hasn't been existed :)

**Pull request merged**
