### PR TITLE
Update job-config.json for 3.9.1

### PR DESCRIPTION
**Pull request by SDawley**
Also  switch 3.10 to next and 3.9.1 to latest in quay.

### CODE REVIEW

**Review by nickboldt — APPROVED** [review]

**Comment by nickboldt** [comment]
I wonder... should the floating tags be:
* for 3.9 :: `3.9`
* for 3.10: `latest`
* for 3.11: `next` 
?

**Comment by SDawley** [comment]
> I wonder... should the floating tags be:
> 
>     * for 3.9 :: `3.9`
> 
>     * for 3.10: `latest`
> 
>     * for 3.11: `next`
>       ?

Ilya specifically asked for 3.9.1 to be latest so it could go on the Developer Sandbox

**Comment by nickboldt** [comment]
Then maybe this is best:
for 3.9 :: latest
for 3.10: next
for 3.11: 3.11

**Comment by SDawley** [comment]
I have chosen option 2, merging.

**Pull request merged**
