### PR TITLE
feat: add code editor

### PR DESCRIPTION
**Pull request by svor**
Signed-off-by: Valerii Svydenko <vsvydenk@redhat.com>

### What does this PR do?
Add VSCode editor meta configuration to Devspaces.

How I tested it:
1. Build plugin registry to get resulted image
2. Retag the image and push it into docker registry
3. Setup instance with Devspaces
4. Update CheCluster CustomResourceDefinition to use my image
5. Started a workspace by using factory https://github.com/devspaces-samples/python-hello-world?che-editor=che-incubator/che-code/insiders

screenshot-console-openshift-console apps ci-ln-s73p04b-72292 origin-ci-int-gce dev rhcloud com-2022 07 21-11_51_21

screenshot-devspaces-openshift-operators apps ci-ln-s73p04b-72292 origin-ci-int-gce dev rhcloud com-2022 07 21-11_50_30

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-2288

### CODE REVIEW

**Review by azatsarynnyy — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
@svor, @nickboldt : so that PR is referencing code-rhel8:3.1 image, would it be possible to cherry-pick changes into the DS 3.1.0 plugin registry: https://github.com/redhat-developer/devspaces/tree/devspaces-3.1-rhel-8 ?

**Comment by nickboldt** [comment]
> @svor, @nickboldt : so that PR is referencing code-rhel8:3.1 image, would it be possible to cherry-pick changes into the DS 3.1.0 plugin registry: https://github.com/redhat-developer/devspaces/tree/devspaces-3.1-rhel-8 ?

everything is possible, given time/resources/desire. 

but do we want this in 3.1? I thought we were feature frozen :D

**Comment by svor** [comment]
> @svor, @nickboldt : so that PR is referencing code-rhel8:3.1 image, would it be possible to cherry-pick changes into the DS 3.1.0 plugin registry: https://github.com/redhat-developer/devspaces/tree/devspaces-3.1-rhel-8 ?

I am not sure it's ready for 3.1. I still want to test some cases

**Comment by nickboldt** [comment]
> I am not sure it's ready for 3.1. I still want to test some cases

As long as there's another way to use the code-rhel8:3.1 image, then +1 to slip to 3.2.

**Comment by svor** [comment]
@azatsarynnyy @dmytro-ndp @nickboldt I've updated the description a bit.
I'm OK to merge it and backport into 3.1, that'll help us to find problems related to the Code editor sooner.
WDYT?

**Comment by azatsarynnyy** [comment]
> ... WDYT?

:rocket:

**Comment by nickboldt** [comment]
cherrypicked to 3.1: 4f6cc835

**Comment by nickboldt** [comment]
Building in:

https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/pluginregistry_3.1/11/
https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/DS_CI/job/pluginregistry_3.x/15/

**Pull request merged**
