### PR TITLE
CRW-3344 update to latest openshift-connnector 0.6.0 plugin (uses odo 2.5.1)

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

[CRW-3344](https://issues.redhat.com/browse/CRW-3344) update to latest openshift-connnector 0.6.0 plugin (uses odo 2.5.1)

Not sure if we need to increase the memory or cpu settings for this:
```
      memoryLimit: 1500Mi
      memoryRequest: 20Mi
      cpuLimit: 800m
      cpuRequest: 30m
```

Also found this overridden setting for ppc64le, applied via https://github.com/redhat-developer/devspaces/blob/devspaces-3-rhel-8/dependencies/che-plugin-registry/build/scripts/swap_plugins_memory.sh#L52

```
replaceField "$YAML_ROOT"/plugins/redhat/vscode-openshift-connector/latest/meta.yaml '.spec.containers[].memoryLimit' "2.5Gi" # CRW-1634
```

Change-Id: Idf6d08c97055b1a35ed18ed973f611ceaf4d65e8
Signed-off-by: Nick Boldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
N/A (or see commit message above for issue number)

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by nickboldt** [comment]
Have not built or tested this, but wanted to get it into a PR form so you could review and approve/merge if you like it. We'll need to backport the change to 3.2, too: https://github.com/redhat-developer/devspaces/pull/808

**Comment by svor** [comment]
We shouldn't merge it before we don't know that it works as the previous version at least

**Comment by vitaliy-guliy** [comment]
I think it's better to use the binary from https://github.com/redhat-developer/devspaces-vscode-extensions/releases/tag/v4003a95

The binary size of the extensions at open-vsix.org is 203Mb. This is much larger than our build, which is 94Mb.
Binary at open-vsix includes binaries of `oc` and `odo`.

We already have that tools inside quay.io/devspaces/udi-rhel8:3.3 image, so no need to include them into .vsix

It's first.
Second, is that `redhat.vscode-openshift-connector` depends on `redhat.vscode-redhat-account`. We have to include it to the registry as well.

I've some issues with running of that extensions in my workspace.
`redhat.vscode-openshift-connector` adds an empty view to the editor, at the first glance everything's ok with it.
But `vscode-redhat-account` extensions hangs while initializing and no response from it

activating-rh-authentication

**Comment by nickboldt** [comment]
Outdated. Plan is to move to 1.0.0 and support odo 3.0 -- see [CRW-3344](https://issues.redhat.com/browse/CRW-3344)

**Pull request closed without merging**
